### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by TorchedSammy** [TorchedSammy/Econode#1]
Currently, there is only 1 item: the sole Electron, which is the smallest/least valuable item.
There should be a lot more items (~30 possibly, *maybe* more) that increase in literal size and their monetary value

**Comment by TorchedSammy** [comment]
item names - their values will be decided separately

- Quark
- Electron
- Transistor
- Logic Circuit
- Breadboard
- FPGA
- CPU
- Embedded Computer
- Smartphone
- Laptop
- Desktop
- Windows Server
- Linux Server
- Server Farm
- Mainframe
- Quantum Computer
- Lunar Quantum Farm
- Computing Solar System
- Quantum Galaxy
- Computational Universe

**Comment by nya1** [comment]
Using electron item as a starting point I have generated the values for the other items

| name                   | base cost | CPS       |
|------------------------|-------------|-----------|
| Quark                  | 15          | 0.005     |
| Electron               | 20          | 0.01      |
| Transistor             | 2000        | 7         |
| Logic Circuit          | 5000        | 21        |
| Breadboard             | 10000       | 63        |
| FPGA                   | 30000       | 189       |
| CPU                    | 90000       | 567       |
| Embedded Computer      | 270000      | 1701      |
| Smartphone             | 810000      | 5103      |
| Laptop                 | 2430000     | 15309     |
| Desktop                | 7290000     | 45927     |
| Windows Server         | 21870000    | 137781    |
| Linux Server           | 65610000    | 413343    |
| Server Farm            | 262440000   | 1240029   |
| Mainframe              | 1049760000  | 3720087   |
| Quantum Computer       | 5248800000  | 11160261  |
| Lunar Quantum Farm     | 26244000000 | 33480783  |
| Computing Solar System | 1.3122E+11  | 100442349 |
| Quantum Galaxy         | 6.561E+11   | 301327047 |
| Computational Universe | 3.2805E+12  | 903981141 |

**Comment by TorchedSammy** [comment]
those values are WAY too high, even for the best item (computational universe) - this isn't cookie clicker which has some wack building values

i'll work on a draft document for price/cps for the new items based on cafe's pricing which is more gradual, though there will be a cut off at the "lunar quantum farm"
